name: x-ray

on:
  push:
    paths:
      - '**.php'
      - 'x-ray.yml'

jobs:
  x-ray:
    name: x-ray
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: [8.3, 8.4]
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run X-Ray
        run: ./vendor/bin/x-ray .
